### PR TITLE
feat: improves client side setup

### PR DESCRIPTION
**Pull request by PedroAugustoRamalhoDuarte**
This PR improves the installation client side setup for all frontend options

## References
https://github.com/inertiajs/inertiajs.com/pull/338
https://inertia-rails.onrender.com/installation/client-side.html#install-dependencies

### CODE REVIEW

**Comment by skryukov** [comment]
Great addition! Do you plan to update vue & svelte installation instructions in this PR as well?

**Comment by PedroAugustoRamalhoDuarte** [comment]
@skryukov Yes I can do that, let's change this PR to Draft

**Comment by PedroAugustoRamalhoDuarte** [comment]
@skryukov I was thinking if is worth to add the import React in the inertia.jsx entrypoints. If we do not use React vite plugin will break the page.

**Comment by skryukov** [comment]
> I was thinking if is worth to add the import React in the inertia.jsx entrypoints. If we do not use React vite plugin will break the page.

The generator and docs are using a simple `.js` and not `.jsx` entrypoint. Does that change the requirement for `import React`?

**Pull request merged**
